SET DATABASE SQL SYNTAX ORA TRUE;

CREATE TABLE IF NOT EXISTS PUBLIC.SAMPLE (
  dept_cd		 VARCHAR(18)
  ,key           INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY
  ,index         INTEGER
  ,guid          VARCHAR(36)
  ,is_active     VARCHAR(1)
  ,balance       NUMERIC(6,2)
  ,picture       VARCHAR(1024)
  ,age           INTEGER
  ,eye_color     VARCHAR(5)
  ,name          VARCHAR(512)
  ,gender        VARCHAR(6)
  ,company       VARCHAR(256)
  ,email         VARCHAR(256)
  ,phone         VARCHAR(64)
  ,address       VARCHAR(512)
  ,about         VARCHAR(1024)
  ,registered    DATE
  ,latitude      NUMERIC(8,6)
  ,longitude     NUMERIC(9,6)
  ,greeting      VARCHAR(1024)
  ,favorite_fruit VARCHAR(64)
  ,file_id     	 VARCHAR(36)
);

CREATE TABLE IF NOT EXISTS PUBLIC.SAMPLE_CODE (
   code         VARCHAR(16)
  ,key			VARCHAR(16)
  ,val			VARCHAR(16)
);
CREATE UNIQUE INDEX IF NOT EXISTS PUBLIC.IDX_SAMPLE_CODE ON PUBLIC.SAMPLE_CODE (code, key);

CREATE TABLE IF NOT EXISTS PUBLIC.SAMPLE_DEPT (
   dept_cd      VARCHAR(16)
  ,p_dept_cd	VARCHAR(16)
  ,dept_nm		VARCHAR(16)
  ,dept_lv		INTEGER
);
CREATE UNIQUE INDEX IF NOT EXISTS PUBLIC.IDX_SAMPLE_DEPT ON PUBLIC.SAMPLE_DEPT (dept_cd);

CREATE TABLE IF NOT EXISTS PUBLIC.FILE (
   file_id     VARCHAR(36)
  ,file_seq			INTEGER GENERATED BY DEFAULT AS IDENTITY (START WITH 1) PRIMARY KEY
  ,file_name	VARCHAR(64)
  ,file_name_ext  VARCHAR(16)
  ,file_size		INTEGER
  ,copy_file_path	VARCHAR(256)
  ,copy_file_name VARCHAR(64)
);
CREATE UNIQUE INDEX IF NOT EXISTS PUBLIC.IDX_FILE ON PUBLIC.FILE (file_id, file_seq);